# Generated by Django 4.1 on 2022-11-30 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='raizen_gasoline_fraud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('outlier_prob', models.FloatField()),
            ],
        ),
    ]
